language: node_js
node_js: stable
script:
  - bash ./gpages_build.sh Twiinlab polyrx-fire dvdchavarri dvdchavarri@gmail.com
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH